// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://slgiikfxjprvqsrciwnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsZ2lpa2Z4anBydnFzcmNpd256Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU4MTc0ODcsImV4cCI6MjA5MTM5MzQ4N30.spffL73VikXNjvs-dfPMPQA128FAwuIGxDbw6E-G7Wo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});